# Generated by Django 5.2.14 on 2026-05-25 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã gửi'), ('served', 'Đã phục vụ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gọi')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bookings.booking', verbose_name='Lịch đặt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn gọi món',
                'verbose_name_plural': 'Danh sách đơn gọi món',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên món')),
                ('price', models.IntegerField(verbose_name='Giá tại thời điểm mua')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Chi tiết món',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Chi tiết yêu cầu')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Trạng thái')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='bookings.booking', verbose_name='Lịch đặt')),
            ],
            options={
                'verbose_name': 'Yêu cầu hỗ trợ',
                'verbose_name_plural': 'Danh sách yêu cầu hỗ trợ',
            },
        ),
    ]
