# Generated by Codex on 2026-05-26

from django.db import migrations, models


def draft_to_submitted(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="draft").update(status="submitted")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(draft_to_submitted, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Đã gửi"),
                    ("preparing", "Đang pha chế"),
                    ("served", "Đã phục vụ"),
                ],
                default="submitted",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
