# Generated by Django 5.2.14 on 2026-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='avatars/default.png', max_length=1000, null=True, verbose_name='Ảnh đại diện'),
        ),
    ]
