# Generated by Django 5.2.14 on 2026-05-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên loại box')),
            ],
            options={
                'verbose_name': 'Loại Box',
                'verbose_name_plural': 'Danh mục loại Box',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Box')),
                ('capacity', models.IntegerField(verbose_name='Sức chứa')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá theo giờ')),
                ('status', models.CharField(choices=[('available', 'Đang trống'), ('pending', 'Chờ phê duyệt'), ('confirmed', 'Chờ Check-in'), ('active', 'Đang sử dụng'), ('completed', 'Đã hoàn thành')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boxes/', verbose_name='Hình ảnh')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxes.boxcategory', verbose_name='Loại Box')),
            ],
            options={
                'verbose_name': 'Không gian Box',
                'verbose_name_plural': 'Danh sách các Box',
            },
        ),
    ]
