# Generated by Django 5.2.14 on 2026-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Hình ảnh'),
        ),
    ]
