# Generated by Django 5.2.14 on 2026-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_alter_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boxes/', verbose_name='Hình ảnh'),
        ),
    ]
