# Generated by Django 5.2.14 on 2026-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú xử lý hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_previous_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Trạng thái trước khi chờ hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lý do khách yêu cầu hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian yêu cầu hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_response_message',
            field=models.TextField(blank=True, verbose_name='Tin nhắn phản hồi hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('confirmed', 'Chờ check-in'), ('active', 'Đang sử dụng'), ('completed', 'Hoàn thành'), ('cancellation_pending', 'Chờ duyệt hủy'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
